"""Offline CSV, JSON, and HTML reports for audio quality audits."""

from __future__ import annotations

import csv
import html
import json
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import List, Optional, Sequence, Tuple, Union

from .quality import (
    AudioQualityResult,
    QualityStatus,
    QualitySummary,
    summarize_quality,
)


@dataclass(frozen=True)
class QualityReportPaths:
    """Paths generated by one quality report write."""

    csv_path: Path
    json_path: Path
    html_path: Path


@dataclass(frozen=True)
class RejectedAudioCopy:
    """Traceability record for a rejected source copied without deleting it."""

    source_path: Path
    copied_path: Path
    reasons: Tuple[str, ...]


def write_quality_reports(
    results: Sequence[AudioQualityResult],
    output_directory: Union[str, Path],
    thresholds: Optional[object] = None,
    *,
    basename: str = "audio_quality",
) -> QualityReportPaths:
    """Write matching CSV/JSON/HTML quality reports for offline inspection."""

    if not basename or Path(basename).name != basename:
        raise ValueError("basename must be a plain filename stem")
    output_dir = Path(output_directory).expanduser().resolve()
    output_dir.mkdir(parents=True, exist_ok=True)
    summary = summarize_quality(results, thresholds)
    csv_path = _write_csv(results, output_dir / "{}.csv".format(basename))
    json_path = _write_json(results, summary, output_dir / "{}.json".format(basename))
    html_path = _write_html(results, summary, output_dir / "{}.html".format(basename))
    return QualityReportPaths(csv_path, json_path, html_path)


def copy_rejected_audio(
    results: Sequence[AudioQualityResult],
    rejected_directory: Union[str, Path],
    *,
    source_root: Optional[Union[str, Path]] = None,
) -> Tuple[RejectedAudioCopy, ...]:
    """Copy FAIL files to a rejection tree and write ``rejection_reasons.csv``.

    Source files are never moved or deleted.  Existing destinations are preserved;
    a short content hash is appended when a name collides.
    """

    destination_root = Path(rejected_directory).expanduser().resolve()
    destination_root.mkdir(parents=True, exist_ok=True)
    root = Path(source_root).expanduser().resolve() if source_root is not None else None
    copied: List[RejectedAudioCopy] = []
    for result in results:
        if result.status is not QualityStatus.FAIL or not result.file_path.is_file():
            continue
        relative = _safe_rejection_relative(result, root)
        destination = destination_root.joinpath(*relative.parts)
        destination.parent.mkdir(parents=True, exist_ok=True)
        if destination.exists():
            suffix = result.sha256[:10] if result.sha256 else "duplicate"
            destination = destination.with_name(
                "{}__{}{}".format(destination.stem, suffix, destination.suffix)
            )
        shutil.copy2(str(result.file_path), str(destination))
        copied.append(RejectedAudioCopy(result.file_path, destination, result.reasons))

    reasons_path = destination_root / "rejection_reasons.csv"
    with reasons_path.open("w", encoding="utf-8-sig", newline="") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=["source_file", "copied_file", "status", "reasons"],
        )
        writer.writeheader()
        for record in copied:
            writer.writerow(
                {
                    "source_file": str(record.source_path),
                    "copied_file": str(record.copied_path.relative_to(destination_root)),
                    "status": QualityStatus.FAIL.value,
                    "reasons": " | ".join(record.reasons),
                }
            )
    return tuple(copied)


def _write_csv(results: Sequence[AudioQualityResult], destination: Path) -> Path:
    fieldnames = [
        "relative_path",
        "sha256",
        "status",
        "decodable",
        "duration_seconds",
        "sample_rate",
        "channels",
        "codec_format",
        "pcm_bit_depth",
        "integrated_lufs",
        "rms_dbfs",
        "sample_peak",
        "sample_peak_dbfs",
        "true_peak_dbfs",
        "crest_factor_db",
        "clipping_sample_ratio",
        "dc_offset",
        "silence_ratio",
        "short_segment_ratio",
        "dynamic_range_db",
        "estimated_noise_floor_dbfs",
        "estimated_snr_db",
        "non_finite_count",
        "channel_difference_db",
        "almost_all_silence",
        "reasons",
        "decode_error",
    ]
    with destination.open("w", encoding="utf-8-sig", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        for result in results:
            row = result.to_dict()
            row["reasons"] = " | ".join(result.reasons)
            writer.writerow({field: row.get(field) for field in fieldnames})
    return destination


def _write_json(
    results: Sequence[AudioQualityResult], summary: QualitySummary, destination: Path
) -> Path:
    payload = {
        "schema_version": 1,
        "summary": summary.to_dict(),
        "files": [result.to_dict() for result in results],
    }
    with destination.open("w", encoding="utf-8") as handle:
        json.dump(payload, handle, ensure_ascii=False, indent=2, allow_nan=False)
        handle.write("\n")
    return destination


def _write_html(
    results: Sequence[AudioQualityResult], summary: QualitySummary, destination: Path
) -> Path:
    rows = "\n".join(_html_row(result) for result in results)
    summary_cards = "".join(
        '<div class="card"><strong>{}</strong><span>{}</span></div>'.format(
            html.escape(label), value
        )
        for label, value in (
            ("Total", summary.total_files),
            ("PASS", summary.pass_files),
            ("WARNING", summary.warning_files),
            ("FAIL", summary.fail_files),
            ("Accepted minutes", "{:.2f}".format(summary.accepted_duration_minutes)),
        )
    )
    document = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Audio quality report</title>
<style>
:root {{ color-scheme: light dark; font-family: system-ui, sans-serif; }}
body {{ margin: 2rem; line-height: 1.45; }}
h1 {{ margin-bottom: .25rem; }}
.summary {{ display: flex; flex-wrap: wrap; gap: .75rem; margin: 1rem 0 1.5rem; }}
.card {{ border: 1px solid #8886; border-radius: .5rem; padding: .65rem .9rem; }}
.card strong, .card span {{ display: block; }}
.card span {{ font-size: 1.3rem; }}
.table-wrap {{ overflow-x: auto; }}
table {{ width: 100%; border-collapse: collapse; font-size: .88rem; }}
th, td {{ border-bottom: 1px solid #8885; padding: .45rem; text-align: left; }}
th {{ position: sticky; top: 0; background: Canvas; }}
.PASS {{ color: #16833a; font-weight: 700; }}
.WARNING {{ color: #b36b00; font-weight: 700; }}
.FAIL {{ color: #c92c2c; font-weight: 700; }}
.reasons {{ min-width: 20rem; white-space: normal; }}
</style>
</head>
<body>
<h1>Audio quality report</h1>
<p>Self-contained offline report. Failed files are excluded from training.</p>
<section class="summary">{summary_cards}</section>
<div class="table-wrap"><table>
<thead><tr>
<th>File</th><th>Status</th><th>Duration (s)</th><th>Rate</th><th>Channels</th>
<th>LUFS</th><th>RMS dBFS</th><th>Peak dBFS</th><th>True peak</th>
<th>Clip ratio</th><th>DC offset</th><th>Silence</th><th>SNR dB</th><th>Reasons</th>
</tr></thead>
<tbody>{rows}</tbody>
</table></div>
</body>
</html>
""".format(summary_cards=summary_cards, rows=rows)
    destination.write_text(document, encoding="utf-8")
    return destination


def _html_row(result: AudioQualityResult) -> str:
    values = (
        result.relative_path,
        result.status.value,
        _number(result.duration_seconds, 3),
        result.sample_rate if result.sample_rate is not None else "",
        result.channels if result.channels is not None else "",
        _number(result.integrated_lufs, 2),
        _number(result.rms_dbfs, 2),
        _number(result.sample_peak_dbfs, 2),
        _number(result.true_peak_dbfs, 2),
        _percent(result.clipping_sample_ratio),
        _number(result.dc_offset, 5),
        _percent(result.silence_ratio),
        _number(result.estimated_snr_db, 2),
        " | ".join(result.reasons),
    )
    cells = []
    for index, value in enumerate(values):
        class_name = ""
        if index == 1:
            class_name = ' class="{}"'.format(result.status.value)
        elif index == len(values) - 1:
            class_name = ' class="reasons"'
        cells.append("<td{}>{}</td>".format(class_name, html.escape(str(value))))
    return "<tr>{}</tr>".format("".join(cells))


def _safe_rejection_relative(result: AudioQualityResult, root: Optional[Path]) -> Path:
    if root is not None:
        try:
            relative = result.file_path.resolve().relative_to(root)
        except ValueError:
            relative = Path(result.file_path.name)
    else:
        relative = Path(result.relative_path)
    safe_parts = [part for part in relative.parts if part not in ("", ".", "..")]
    return Path(*safe_parts) if safe_parts else Path(result.file_path.name)


def _number(value: Optional[float], digits: int) -> str:
    return "" if value is None else ("{:.%df}" % digits).format(value)


def _percent(value: Optional[float]) -> str:
    return "" if value is None else "{:.3%}".format(value)
